<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>CLM_AM_and_CM_receives_contract_expired_notification</fullName>
        <description>CLM AM and CM receives contract expired notification</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderAddress>clm.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Expiration_Notification</template>
    </alerts>
    <alerts>
        <fullName>CLM_AM_and_CM_receives_reminder_notification</fullName>
        <description>CLM AM and CM receives reminder notification</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Expiration_Reminder</template>
    </alerts>
    <alerts>
        <fullName>CLM_AM_and_CM_receives_reminder_notification_1</fullName>
        <description>CLM AM and CM receives reminder notification 1</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Expiration_Reminder</template>
    </alerts>
    <alerts>
        <fullName>CLM_AM_and_CM_receives_reminder_notification_2</fullName>
        <description>CLM AM and CM receives reminder notification 2</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Expiration_Reminder</template>
    </alerts>
    <alerts>
        <fullName>CLM_AM_and_CM_receives_reminder_notification_3</fullName>
        <description>CLM AM and CM receives reminder notification 3</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Expiration_Reminder</template>
    </alerts>
    <alerts>
        <fullName>CLM_AM_and_CM_receives_reminder_notification_4</fullName>
        <description>CLM AM and CM receives reminder notification 4</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Expiration_Reminder</template>
    </alerts>
    <alerts>
        <fullName>CLM_AM_receives_reminder_before_six_months</fullName>
        <description>CLM AM receives reminder before six months</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Expiration_Reminder</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Activation_Notification</fullName>
        <description>CLM Agreement Activation Notification</description>
        <protected>false</protected>
        <recipients>
            <recipient>CLM_CO_NAM_PCM</recipient>
            <type>group</type>
        </recipients>
        <senderAddress>clm.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Activation_Notification</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Expiry_Notification_for_Care</fullName>
        <description>Agreement Expiry Notification for Care</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Expiry_Notification_for_Care</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Fully_Signed_notification_to_APJ_GSS</fullName>
        <ccEmails>contractupload.gss-apj@nokia.com</ccEmails>
        <description>CLM Agreement Fully Signed notification to APJ GSS</description>
        <protected>false</protected>
        <recipients>
            <recipient>CLM_Project_Contract_Managers_Team</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Notification_when_an_agreement_is_Fully_signed</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Fully_Signed_notification_to_EUROPE_GSS</fullName>
        <ccEmails>contractupload.gss-europe@nokia.com</ccEmails>
        <description>CLM Agreement Fully Signed notification to EUROPE GSS</description>
        <protected>false</protected>
        <recipients>
            <recipient>CLM_Project_Contract_Managers_Team</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Notification_when_an_agreement_is_Fully_signed</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Fully_Signed_notification_to_GCHN_GSS</fullName>
        <ccEmails>contractupload.gss-gchn@nokia-sbell.com</ccEmails>
        <description>CLM Agreement Fully Signed notification to GCHN GSS</description>
        <protected>false</protected>
        <recipients>
            <recipient>CLM_Project_Contract_Managers_Team</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Notification_when_an_agreement_is_Fully_signed</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Fully_Signed_notification_to_India_GSS</fullName>
        <ccEmails>contractupload.gss-india@nokia.com</ccEmails>
        <description>CLM Agreement Fully Signed notification to India GSS</description>
        <protected>false</protected>
        <recipients>
            <recipient>CLM_Project_Contract_Managers_Team</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Notification_when_an_agreement_is_Fully_signed</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Fully_Signed_notification_to_LAT_GSS</fullName>
        <ccEmails>contractupload.gss-lat@nokia.com</ccEmails>
        <description>CLM Agreement Fully Signed notification to LAT GSS</description>
        <protected>false</protected>
        <recipients>
            <recipient>CLM_Project_Contract_Managers_Team</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Notification_when_an_agreement_is_Fully_signed</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Fully_Signed_notification_to_MEA_GSS</fullName>
        <ccEmails>contractupload.gss-mea@nokia.com</ccEmails>
        <description>CLM Agreement Fully Signed notification to MEA GSS</description>
        <protected>false</protected>
        <recipients>
            <recipient>CLM_Project_Contract_Managers_Team</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Notification_when_an_agreement_is_Fully_signed</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Fully_Signed_notification_to_NAM_GSS</fullName>
        <ccEmails>contractupload.gss-nam@nokia.com</ccEmails>
        <description>CLM Agreement Fully Signed notification to NAM GSS</description>
        <protected>false</protected>
        <recipients>
            <recipient>CLM_Project_Contract_Managers_Team</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Notification_when_an_agreement_is_Fully_signed</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Returned_to_Requestor</fullName>
        <description>CLM Agreement Returned to Requestor</description>
        <protected>false</protected>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_CM_Returns_to_Requestor</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Submission_alert_to_Individual_CM</fullName>
        <description>CLM Agreement Submission alert to Individual CM</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>clm.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Contract_request_Individual_CM</template>
    </alerts>
    <alerts>
        <fullName>CLM_Agreement_Termination</fullName>
        <description>CLM Agreement Termination</description>
        <protected>false</protected>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Termination</template>
    </alerts>
    <alerts>
        <fullName>CLM_Contract_Request_is_created_but_not_submitted_to_L_C</fullName>
        <description>CLM Contract Request is created but not submitted to Legal</description>
        <protected>false</protected>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderAddress>clm.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Contract_Request_is_created_but_not_submitted_to_L_C</template>
    </alerts>
    <alerts>
        <fullName>CLM_Email_Notification_to_NDA_Helpdesk_Queue</fullName>
        <description>CLM Email Notification to NDA Helpdesk Queue</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Email_Notification_to_NDA_Helpdesk_Queue</template>
    </alerts>
    <alerts>
        <fullName>CLM_Individual_Ownership_of_CM_Queue</fullName>
        <description>CLM Individual Ownership of CM Queue</description>
        <protected>false</protected>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderAddress>clm.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_CM_takes_Contract_Request</template>
    </alerts>
    <alerts>
        <fullName>CLM_Notification_when_an_agreement_is_Fully_signed</fullName>
        <description>CLM Notification when an agreement is Fully signed</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Notification_when_an_agreement_is_Fully_signed</template>
    </alerts>
    <alerts>
        <fullName>CLM_PCM_Receives_Contract_Expired_Notification</fullName>
        <description>CLM PCM Receives Contract Expired Notification</description>
        <protected>false</protected>
        <recipients>
            <recipient>CLM_CO_NAM_PCM</recipient>
            <type>group</type>
        </recipients>
        <senderAddress>clm.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Agreement_Expiration_Notification</template>
    </alerts>
    <alerts>
        <fullName>CLM_Ready_for_Review</fullName>
        <description>CLM Ready for Review</description>
        <protected>false</protected>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Ready_For_Review</template>
    </alerts>
    <alerts>
        <fullName>CLM_Ready_for_Signatures</fullName>
        <description>CLM Ready for Signatures</description>
        <protected>false</protected>
        <recipients>
            <field>Apttus__Requestor__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Apttus__ApttusEmailTemplates/CLM_Ready_for_Signatures</template>
    </alerts>
</Workflow>
