<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>CH_Case_Owner_Email_Notification_Alert</fullName>
        <description>CH Case Owner Email Notification Alert</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>CH_EmailTemplates/CH_Case_Owner_Email_Notification_Alert</template>
    </alerts>
    <alerts>
        <fullName>CH_NotificationAlertOnEmailLimit</fullName>
        <description>CH NotificationAlertOnEmailLimit</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>unfiled$public/CH_NotificationOnEmailLimitExceed</template>
    </alerts>
    <alerts>
        <fullName>CH_Send_Email_Notifications</fullName>
        <description>CH Send Email Notifications</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>CH_Auto_Case_Handling/CH_SendEmailNotification</template>
    </alerts>
    <alerts>
        <fullName>HWS_Damaged_Service_Quote_Customer_Email</fullName>
        <description>HWS Service Quote Customer Email for Damaged Parts</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail1__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail2__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail3__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>support.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_Return_Exclusions_Notification</template>
    </alerts>
    <alerts>
        <fullName>HWS_Order_Acknowledgement_Escalated_Case</fullName>
        <description>Created for NOKIASC-36876</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail1__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail2__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail3__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_Order_Acknowledgement_Escalated_Case</template>
    </alerts>
    <alerts>
        <fullName>HWS_Pending_Order_Summary_Auto_split</fullName>
        <description>HWS_Pending Order Summary Auto split</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail1__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail2__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail3__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_Pending_Order_Summary_Auto_Split</template>
    </alerts>
    <alerts>
        <fullName>HWS_Pending_Order_Summary_Manual_Split_Email_Alert</fullName>
        <description>HWS_Pending Order Summary Manual Split Email Alert</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail1__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail2__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail3__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_Pending_Order_Summary_Manual_Split</template>
    </alerts>
    <alerts>
        <fullName>HWS_Quotation_OwnerReassignment_Email</fullName>
        <description>HWS_Quotation_OwnerReassignment_Email</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail1__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail2__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail3__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>support.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_Quotation_OwnerReassignment_Email</template>
    </alerts>
    <alerts>
        <fullName>HWS_Quotation_WG_Assignment</fullName>
        <description>HWS_Quotation_WG_Assignment</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail1__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail2__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail3__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>support.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_Quotation_WG_Assignment_Email</template>
    </alerts>
    <alerts>
        <fullName>HWS_Request_HW_FMA_RCA_Sharepoint_Alert</fullName>
        <description>HWS Request HW FMA RCA Sharepoint Alert</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>support.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_Request_HW_FMA_RCA_Sharepoint_New</template>
    </alerts>
    <alerts>
        <fullName>HWS_Service_Quote_Escalation_Email</fullName>
        <description>HWS Service Quote Escalation Email</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>support.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_Quote_Escalation_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>HWS_Service_Quote_Unreturn_Email_Alert</fullName>
        <description>HWS Service Quote Unreturn Email Alert</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail1__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail2__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_BindEmail3__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>support.services@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_Unreturned_Parts_Notification_1</template>
    </alerts>
    <alerts>
        <fullName>HWS_WARRANTY_WORKGROUP_EMAIL_4</fullName>
        <description>HWS_WARRANTY WORKGROUP EMAIL-4</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_WGAssignEmails_WarrTypeQueue_4</template>
    </alerts>
    <alerts>
        <fullName>HWS_Workgroup_Email_Reassignment_Alert</fullName>
        <description>HWS Workgroup Email Reassignment Alert</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_WGEmailAssignment</template>
    </alerts>
    <alerts>
        <fullName>QUOTATION_WORKGROUP_EMAIL_Alert_1</fullName>
        <description>QUOTATION WORKGROUP EMAIL Alert-1</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_WGAssignEmails_QuoteTypeQueue_1</template>
    </alerts>
    <alerts>
        <fullName>QUOTATION_WORKGROUP_EMAIL_Alert_for_BOTH_WORKGROUP_TYPES_2</fullName>
        <description>QUOTATION WORKGROUP EMAIL Alert for BOTH WORKGROUP TYPES-2</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_WGAssignEmails_QuoteReq_2</template>
    </alerts>
    <alerts>
        <fullName>WARRANTY_QUOTATION_WORKGROUP_EMAIL_3</fullName>
        <description>WARRANTY &amp; QUOTATION WORKGROUP EMAIL-3</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Bind15__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>salesforce.no_reply@nokia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>HWS_Email_Templates/HWS_WGAssignEmails_Warr_QuoteQueue_3</template>
    </alerts>
</Workflow>
