<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>CH_RequestRejectRequestEmail</fullName>
        <description>CH_RequestRejectRequestEmail</description>
        <protected>false</protected>
        <recipients>
            <field>CH_EscalationRequester__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Manage_Escalation/CH_ME_SendRejectTORequester</template>
    </alerts>
    <alerts>
        <fullName>CH_RequestSupportToAllPartners</fullName>
        <description>CH_RequestSupportToAllPartners</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Escalation_Partner1_Non_SF_User__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_2_Non_SF_User__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_3_Non_SF_User__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_4_Non_SF_User__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_5_Non_SF_User__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_1__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_2__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_3__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_4__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_5__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Manage_Escalation/CH_Management_Escalation_Resources_Requested</template>
    </alerts>
    <alerts>
        <fullName>CH_SendClosureEmailToAllPartners</fullName>
        <description>CH_SendClosureEmailToAllPartners</description>
        <protected>false</protected>
        <recipients>
            <field>CH_Escalation_Partner1_Non_SF_User__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_2_Non_SF_User__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_3_Non_SF_User__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_4_Non_SF_User__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_5_Non_SF_User__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_1__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_2__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_3__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_4__c</field>
            <type>userLookup</type>
        </recipients>
        <recipients>
            <field>CH_Escalation_Partner_5__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Manage_Escalation/CH_MEClosureEmailToPartners</template>
    </alerts>
    <alerts>
        <fullName>CH_SendEscalationRequestEmail</fullName>
        <description>CH_SendEscalationRequestEmail</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Manage_Escalation/CH_ME_SendEscalationRequest</template>
    </alerts>
    <alerts>
        <fullName>CH_Send_to_Requester</fullName>
        <description>CH_Send to Requester</description>
        <protected>false</protected>
        <recipients>
            <field>CH_EscalationRequester__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Manage_Escalation/CH_Email_Template_to_Requester</template>
    </alerts>
</Workflow>
