<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <fieldUpdates>
        <fullName>CH_CA_Timeslot_Member_Duplicate_Check</fullName>
        <field>CH_Duplicate_Check__c</field>
        <formula>CH_Workgroup_Schedule_Timeslot__c + CH_Workgroup_Member__c</formula>
        <name>CH_CA_Timeslot_Member_Duplicate_Check</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CH_GridBuddy_Schedule_Id</fullName>
        <field>CH_Schedule_Id__c</field>
        <formula>CASESAFEID(CH_Workgroup_Schedule_Timeslot__r.CH_Workgroup_Schedule__c)</formula>
        <name>CH_GridBuddy_Schedule_Id</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CH_GridBuddy_Schedule_Name</fullName>
        <field>CH_Schedule_Name__c</field>
        <formula>CH_Workgroup_Schedule_Timeslot__r.CH_Workgroup_Schedule__r.Name</formula>
        <name>CH_GridBuddy_Schedule_Name</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CH_GridBuddy_TimeSlot_Name</fullName>
        <field>CH_Schedule_Time_Slot_Name__c</field>
        <formula>CH_Workgroup_Schedule_Timeslot__r.Name</formula>
        <name>CH_GridBuddy_TimeSlot_Name</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CH_GridBuddy_Workgroup_Id</fullName>
        <field>CH_Workgroup_Id__c</field>
        <formula>CASESAFEID(CH_Workgroup_Schedule_Timeslot__r.CH_Workgroup_Schedule__r.CH_Workgroup__c)</formula>
        <name>CH_GridBuddy_Workgroup_Id</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CH_GridBuddy_Workgroup_Name</fullName>
        <field>CH_Workgroup_Name__c</field>
        <formula>CH_Workgroup_Schedule_Timeslot__r.CH_Workgroup_Schedule__r.CH_Workgroup__r.Name</formula>
        <name>CH_GridBuddy_Workgroup_Name</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <rules>
        <fullName>CH_CA_Save_WorkgroupMemberId_For_Duplication_Check</fullName>
        <actions>
            <name>CH_CA_Timeslot_Member_Duplicate_Check</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>true</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>CH_CA_WGMTA</fullName>
        <actions>
            <name>CH_GridBuddy_Schedule_Id</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CH_GridBuddy_Schedule_Name</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CH_GridBuddy_TimeSlot_Name</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CH_GridBuddy_Workgroup_Id</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CH_GridBuddy_Workgroup_Name</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>true</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
</Workflow>
